root {
  replacement_target: "replacement_target"
  text {
    text: "Linux Settings UI"
  }
}
onload_actions_list {
  actions {
    action_id: "get_all_settings"
  }
}
subscriptions {
  index: 1,
  actions_list {
    actions {
      action_id: "handleSettingsChange"
    }
  }
}
configured_actions {
  key: "get_all_settings"
  value {
    actions {
      apply_template_to_context_action {
        template: "{ 'action': 'get_all_settings' }"
        target_id: "JsonStr"
      }
    }
    actions {
      parse_action {
        context_id: "JsonStr"
        target_id: "Json"
        string_to_json: true
      }
    }
    actions {
      serialize_action {
        context_id: "Json"
        target_id: "JsonSerialized"
        json: true
      }
    }
    actions {
      server_action {
        channel_index: 1
        context_id: "JsonSerialized"
      }
    }
  }
}
configured_actions {
  key: "handleSettingsChange",
  value {
    actions {
      parse_action {
        context_id: "$root"
        string_to_json: true
      }
    }
    actions {
      jq_action {
        context_id: "obj"
        transform_expression: ".{{key}}"
        target_id: "{{target_id}}"
      }
    }
    actions {
      debug {
        context_id: "."
      }
    }
  }
}
